image: node:latest

before_script:
  - npm install --save-dev

pages:
  stage: deploy
  script:
    - ./node_modules/gulp/bin/gulp.js --gulpfile gulpfile.js
  artifacts:
    paths:
      - public
  only:
    - master
